### ISSUE TITLE
docker-sync with unison

### ISSUE THREAD

**Issue by u007** [EugenMayer/docker-sync#545]
### Error/Feature Requestion/Docs
docker instance shows:
```
user with uid 0 already exist and its root
/entrypoint.sh: ignoring /docker-entrypoint.d/*
/usr/lib/python2.7/site-packages/supervisor/options.py:298: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Error: Format string '%(ENV_APP_VOLUME)s' for 'program:unison.directory' contains names ('ENV_APP_VOLUME') which cannot be expanded. Available names: ENV_GROUP, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_OWNER, ENV_OWNER_HOMEDIR, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV_TZ, ENV_UNISON_DIR, ENV_UNISON_EXCLUDES, ENV_VOLUME, group_name, here, host_node_name, process_num, program_name in section 'program:unison' (file: '/etc/supervisor.conf.d/supervisor.daemon.conf')
For help, use /usr/bin/supervisord -h
```

### Docker Driver
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

### Sync strategy
unison

### your docker-sync.yml
```
version: "2"

options:
  verbose: true
  max_attempt: 10
syncs:
  ossdc_volume: # tip: add -sync and you keep consistent names as a convention
    src: './'
    sync_strategy: 'unison'
    sync_excludes: ['.git']

```

### OS
osx 10.13.2

**Comment by EugenMayer** [comment]
dupe

**Comment by u007** [comment]
which issue is it? is it still open?

**Comment by EugenMayer** [comment]
@u007 https://github.com/EugenMayer/docker-sync/issues/545 closed and fixed with 0.5.5

**Comment by u007** [comment]
nice :) thank you, where do i get latest gem?

**Comment by u007** [comment]
nvm, i found out i could use this to install github version

https://github.com/rdp/specific_install

**Comment by michalkleiner** [comment]
@u007 or `gem uninstall docker-sync && gem install docker-sync`

**Comment by u007** [comment]
after fail to get update on native_osx, i removed my volume, and finally get to run with unison sync strategy, and my files is still not synced
